package com.airline.service;

import com.airline.domain.Invoice;
import com.airline.domain.InvoiceLineItem;
import com.airline.notification.NotificationRecipientResolver;
import jakarta.mail.internet.MimeMessage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Dispatches approved invoices to role- and dimension-authorized airline users.
 * Attaches both the application-contract invoice XML and PDF to the outgoing message.
 */
@Service
public class InvoiceDispatchService {

    private static final Logger logger = LoggerFactory.getLogger(InvoiceDispatchService.class);

    private final JavaMailSender mailSender;
    private final NotificationRecipientResolver recipientResolver;

    @Value("${app.mail.from:noreply@ghcp.internal}")
    private String fromAddress;

    @Value("${app.mail.dispatch-enabled:true}")
    private boolean dispatchEnabled;

    @Value("${app.mail.simulate-delivery:false}")
    private boolean simulateDelivery;

    public InvoiceDispatchService(
            JavaMailSender mailSender, NotificationRecipientResolver recipientResolver) {
        this.mailSender = mailSender;
        this.recipientResolver = recipientResolver;
    }

    /**
     * Sends the invoice email to the airline.
     * @param invoice  the APPROVED invoice being dispatched
     * @param xmlBytes the generated invoice XML file bytes
     * @param pdfBytes the generated PDF file bytes
     */
    public void dispatch(Invoice invoice, byte[] xmlBytes, byte[] pdfBytes) {
        if (simulateDelivery) {
            logger.info("Simulated successful invoice delivery for invoice ID: {}", invoice.getId());
            return;
        }
        if (!dispatchEnabled) {
            throw new IllegalStateException("Invoice email dispatch is disabled");
        }

        List<String> recipients = resolveAirlineEmails(invoice);
        if (recipients.isEmpty()) {
            throw new IllegalStateException("No authorized airline invoice recipients were found");
        }
        String subject = String.format("Invoice %s from Ground Handler %s",
                invoice.getInvoiceNumber(), invoice.getSupplierId());

        String body = buildEmailBody(invoice);
        String xmlFilename = String.format("invoice-%s.xml", invoice.getInvoiceNumber());
        String pdfFilename = String.format("invoice-%s.pdf", invoice.getInvoiceNumber());

        MimeMessage message = mailSender.createMimeMessage();
        try {
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setFrom(fromAddress);
            helper.setTo(recipients.toArray(String[]::new));
            helper.setSubject(subject);
            helper.setText(body, false);
            helper.addAttachment(xmlFilename, () -> new java.io.ByteArrayInputStream(xmlBytes), "application/xml");
            helper.addAttachment(pdfFilename, () -> new java.io.ByteArrayInputStream(pdfBytes), "application/pdf");
            mailSender.send(message);
        } catch (Exception e) {
            throw new IllegalStateException("Invoice email dispatch failed", e);
        }
    }

    private List<String> resolveAirlineEmails(Invoice invoice) {
        Set<String> chargeCodes = invoice.getLineItems() == null
                ? Set.of()
                : invoice.getLineItems().stream()
                        .map(InvoiceLineItem::getChargeCode)
                        .collect(Collectors.toUnmodifiableSet());
        return recipientResolver.resolve(
                invoice.getAirlineId(),
                Set.of("INVOICE_REVIEWER"),
                invoice.getAirportCode(),
                invoice.getAirlineId(),
                chargeCodes);
    }

    private String buildEmailBody(Invoice invoice) {
        return String.format("""
                Dear %s,

                Please find attached Invoice %s from %s for services at %s.

                Invoice Details:
                  Invoice Number : %s
                  Issue Date     : %s
                  Due Date       : %s
                  Currency       : %s
                  Total Amount   : %s %s

                Two attachments are included:
                  1. GHCP invoice XML (validated against the application contract)
                  2. PDF invoice for your records

                Please process payment by the due date indicated.

                This is an automated message generated by the Ground Handling Cost Management Platform.
                """,
                invoice.getAirlineId(),
                invoice.getInvoiceNumber(),
                invoice.getSupplierId(),
                invoice.getAirportCode(),
                invoice.getInvoiceNumber(),
                invoice.getIssueDate(),
                invoice.getDueDate(),
                invoice.getCurrency(),
                invoice.getTotalAmount(),
                invoice.getCurrency()
        );
    }
}
