package com.airline.service;

import com.airline.domain.Invoice;
import jakarta.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

/**
 * Dispatches approved invoices via email to the airline-configured email addresses.
 * Attaches both the IATA IS-XML file and the PDF to the outgoing message.
 */
@Service
public class InvoiceDispatchService {

    private final JavaMailSender mailSender;

    @Value("${app.mail.from:noreply@ghcp.internal}")
    private String fromAddress;

    @Value("${app.mail.dispatch-enabled:true}")
    private boolean dispatchEnabled;

    public InvoiceDispatchService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    /**
     * Sends the invoice email to the airline.
     * The airline email is derived from the airlineId — in production this is
     * looked up from the SupplierConfiguration table. Here we use a dev placeholder.
     *
     * @param invoice  the SENT invoice
     * @param xmlBytes the generated IATA IS-XML file bytes
     * @param pdfBytes the generated PDF file bytes
     */
    public void dispatch(Invoice invoice, byte[] xmlBytes, byte[] pdfBytes) {
        if (!dispatchEnabled) {
            return;
        }

        try {
            String toEmail = resolveAirlineEmail(invoice);
            String subject = String.format("Invoice %s from Ground Handler %s",
                    invoice.getInvoiceNumber(), invoice.getSupplierId());

            String body = buildEmailBody(invoice);
            String xmlFilename = String.format("invoice-%s.xml", invoice.getInvoiceNumber());
            String pdfFilename = String.format("invoice-%s.pdf", invoice.getInvoiceNumber());

            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setFrom(fromAddress);
            helper.setTo(toEmail);
            helper.setSubject(subject);
            helper.setText(body, false);
            helper.addAttachment(xmlFilename, () -> new java.io.ByteArrayInputStream(xmlBytes), "application/xml");
            helper.addAttachment(pdfFilename, () -> new java.io.ByteArrayInputStream(pdfBytes), "application/pdf");

            mailSender.send(message);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to dispatch invoice email: " + e.getMessage(), e);
        }
    }

    private String resolveAirlineEmail(Invoice invoice) {
        // In a full implementation, this looks up the supplier's configured
        // airline email from the SupplierConfiguration table.
        // For now, we use a predictable dev address routed to Mailhog.
        return invoice.getAirlineId().toLowerCase() + "@airline.ghcp.dev";
    }

    private String buildEmailBody(Invoice invoice) {
        return String.format("""
                Dear %s,

                Please find attached Invoice %s from %s for services at %s.

                Invoice Details:
                  Invoice Number : %s
                  Issue Date     : %s
                  Due Date       : %s
                  Currency       : %s
                  Total Amount   : %s %s

                Two attachments are included:
                  1. IATA IS-XML invoice (IS P3 compliant)
                  2. PDF invoice for your records

                Please process payment by the due date indicated.

                This is an automated message generated by the Ground Handling Cost Management Platform.
                """,
                invoice.getAirlineId(),
                invoice.getInvoiceNumber(),
                invoice.getSupplierId(),
                invoice.getAirportCode(),
                invoice.getInvoiceNumber(),
                invoice.getIssueDate(),
                invoice.getDueDate(),
                invoice.getCurrency(),
                invoice.getTotalAmount(),
                invoice.getCurrency()
        );
    }
}
